Importa numpy

In [1]:
import numpy as np

crea un numpy array que tenga la siguente estructura

```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```

llamalo `array`

In [2]:
array = np.array([
    [1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
                )

averigua la forma del array

In [3]:
array.shape

(5, 3)

Selecciona la segunda columna del array

In [4]:
array

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [5]:
array[:,1]

array([ 6,  7,  8,  9, 10])

 Crea un vector con los valores del 15 al 55, llamalo array2
    
*pista: usa np.arange*

In [6]:
np.arange

<function numpy.arange>

In [7]:
array2 = np.arange(15,56)
array2

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

asigna el valor 23 a la quinta posicion del array2

In [8]:
array2[4] = 23
array2

array([15, 16, 17, 18, 23, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

convierte array2 del revés (es decir `[55,54,....,15]`

In [9]:
array2[::-1]

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 23, 18, 17, 16, 15])

Crea una matriz diagonal donde los elementos de la diagonal sean los 5 primeros valores pares de array2, llamala `matriz_diag`

*pista: usa np.diag*

In [10]:
array2

array([15, 16, 17, 18, 23, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [11]:
np.diag(array2[1::2][:5])

array([[16,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 20,  0,  0],
       [ 0,  0,  0, 22,  0],
       [ 0,  0,  0,  0, 24]])

In [12]:
matriz_diag = np.diag(array2[1::2][:5])
matriz_diag

array([[16,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 20,  0,  0],
       [ 0,  0,  0, 22,  0],
       [ 0,  0,  0,  0, 24]])

Imprime el numero de dimensiones de `matriz_diag`

In [13]:
matriz_diag.ndim

2

Crea una matriz con números aleatorios de tamaño 5x3 (5 filas por 3 columnas), llamala `matriz`

In [14]:
np.random.random?

In [15]:
matriz = np.random.random((5,3))
matriz

array([[0.80211417, 0.58725008, 0.1985695 ],
       [0.03332242, 0.49209772, 0.71955444],
       [0.97048077, 0.56062579, 0.33865819],
       [0.62127058, 0.07254791, 0.3590387 ],
       [0.37833962, 0.55024908, 0.63794233]])

multiplica `matriz` por `matriz_diag`

In [16]:
matriz.shape

(5, 3)

In [17]:
matriz_diag.shape

(5, 5)

In [18]:
matriz @ matriz_diag

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 3)

In [19]:
matriz.T.shape

(3, 5)

In [20]:
matriz.T @ matriz_diag

array([[12.83382672,  0.59980348, 19.40961545, 13.66795275,  9.08015079],
       [ 9.39600129,  8.85775901, 11.21251574,  1.59605407, 13.20597781],
       [ 3.17711199, 12.95197996,  6.77316388,  7.8988514 , 15.31061598]])