### Regularización en Keras

In [1]:
%load_ext watermark
%watermark

2018-03-07T20:56:52+01:00

CPython 3.6.4
IPython 6.2.1

compiler   : GCC 4.8.2 20140120 (Red Hat 4.8.2-15)
system     : Linux
release    : 4.13.0-36-generic
machine    : x86_64
processor  : x86_64
CPU cores  : 8
interpreter: 64bit


In [1]:
from IPython.display import Image


import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (7, 7)

# Cargamos los datos

En deep learning no se suele hacer validación cruzada (a menos que el tamaño del dataset y el tiempo de entrenamiento lo permita). En lugar de eso se hacen simples separaciónes entre datos de entrenamiento y de validación.

In [2]:
from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

Using TensorFlow backend.


In [3]:
x_train.shape

(60000, 28, 28)

In [4]:
x_train[0].shape

(28, 28)

In [7]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [5]:
from ipywidgets import interact, IntSlider

In [6]:
@interact(i=IntSlider(min=0,max=50,step=1,value=1))
def dibujar_numero(i):
    plt.imshow(x_train[i], cmap="gray")
    plt.title("Número {}".format(y_train[i]))

A Jupyter Widget

In [7]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten

In [8]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [9]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [10]:
x_train[0].shape

(28, 28)

In [11]:
x_train_plano = x_train.reshape(x_train.shape[0],28*28)
x_test_plano = x_test.reshape(x_test.shape[0],28*28)

In [12]:
x_train_plano[0].shape

(784,)

In [13]:
x_train_plano[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [14]:
from keras.utils.np_utils import to_categorical

In [15]:
y_train[:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [16]:
y_train_one_hot = to_categorical(y_train)
y_test_one_hot = to_categorical(y_test)

In [17]:
y_train_one_hot[:10]

array([[ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]])

In [19]:
modelo = Sequential()
modelo.add(Dense(50, activation="relu", input_shape=(784,)))
modelo.add(Dense(250, activation="relu"))
modelo.add(Dense(np.unique(y_train).shape[0], activation="softmax"))

modelo.compile(optimizer="sgd", loss="categorical_crossentropy", 
               metrics=["accuracy"])

modelo.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 50)                39250     
_________________________________________________________________
dense_5 (Dense)              (None, 250)               12750     
_________________________________________________________________
dense_6 (Dense)              (None, 10)                2510      
Total params: 54,510
Trainable params: 54,510
Non-trainable params: 0
_________________________________________________________________


In [20]:
modelo.fit(x_train_plano, y_train_one_hot, epochs=50, batch_size=1000, verbose=0);

Vamos a ver ahora como se compara el funcionamiento del modelo respecto a los datos de entrenamiento y los de test. 

In [21]:
RESULTADOS = {}

In [22]:
modelo.metrics_names

['loss', 'acc']

In [23]:
evaluacion_train = modelo.evaluate(x_train_plano, y_train_one_hot)
evaluacion_train

60000/60000 [==============================] - 2s 27us/step


[0.065759703718370782, 0.99341666666666661]

In [24]:
evaluacion_test = modelo.evaluate(x_test_plano, y_test_one_hot)
evaluacion_test

10000/10000 [==============================] - 0s 28us/step


[0.33679755761827446, 0.94869999999999999]

In [25]:
RESULTADOS["sin_regularizacion"] = [evaluacion_train[1], evaluacion_test[1]]

### Regularización l1, o l2

Keras permite regularizar los pesos, los sesgos (bias) y las activaciones de  forma independiente, pasando el parámetro `kernel_regularizer`, `bias_regularizer` y `activity_regularizer` respectivamente.

Keras tiene los penalizadores `l1`, `l2` y `l1_l2` (elasticnet)

In [26]:
from keras import regularizers

modelo_l2 = Sequential()
modelo_l2.add(Dense(50, activation="relu", input_shape=(784,)))
modelo_l2.add(Dense(250, activation="relu", kernel_regularizer=regularizers.l2(0.01)))
modelo_l2.add(Dense(np.unique(y_train).shape[0], activation="softmax"))

modelo_l2.compile(optimizer="sgd", loss="categorical_crossentropy", 
               metrics=["accuracy"])

modelo_l2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 50)                39250     
_________________________________________________________________
dense_8 (Dense)              (None, 250)               12750     
_________________________________________________________________
dense_9 (Dense)              (None, 10)                2510      
Total params: 54,510
Trainable params: 54,510
Non-trainable params: 0
_________________________________________________________________


In [27]:
modelo_l2.fit(x_train_plano, y_train_one_hot, verbose=0, epochs=50, batch_size=1000);

In [28]:
acc_train = modelo_l2.evaluate(x_train_plano, y_train_one_hot)[1]
acc_train

60000/60000 [==============================] - 2s 27us/step


0.97463333333333335

In [29]:
acc_test = modelo.evaluate(x_test_plano, y_test_one_hot)[1]
acc_test

10000/10000 [==============================] - 0s 28us/step


0.94869999999999999

In [30]:
RESULTADOS["regularizacion_l2"] = [acc_train, acc_test]

Hacemos lo mismo pero con regularización l1

In [31]:
modelo_l1 = Sequential()
modelo_l1.add(Dense(50, activation="relu", input_shape=(784,)))
modelo_l1.add(Dense(250, activation="relu", kernel_regularizer=regularizers.l1(0.01)))
modelo_l1.add(Dense(np.unique(y_train).shape[0], activation="softmax"))

modelo_l1.compile(optimizer="sgd", loss="categorical_crossentropy", 
               metrics=["accuracy"])

modelo_l1.fit(x_train_plano, y_train_one_hot, verbose=0, epochs=50, batch_size=1000)

acc_train = modelo_l1.evaluate(x_train_plano, y_train_one_hot)[1]
acc_test = modelo_l1.evaluate(x_test_plano, y_test_one_hot)[1]

RESULTADOS["regularizacion_l1"] = [acc_train, acc_test]

10000/10000 [==============================] - 0s 26us/step


In [33]:
print(acc_train, acc_test)

0.9588 0.9504


### Dropout

Ahora vamos a añadir Dropout a la misma red. Dropout simplemente ignora un porcentaje `p` de las unidades (neuronas) en cada iteración del entrenamiento (forward prop y backprop)

In [34]:
from keras.layers import Dropout

In [35]:
modelo_dropout = Sequential()
modelo_dropout.add(Dense(50, activation="relu", input_shape=(784,)))
modelo_dropout.add(Dense(250, activation="relu"))
modelo_dropout.add(Dropout(0.2))
modelo_dropout.add(Dense(np.unique(y_train).shape[0], activation="softmax"))

modelo_dropout.compile(optimizer="sgd", loss="categorical_crossentropy", 
               metrics=["accuracy"])

modelo_dropout.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_13 (Dense)             (None, 50)                39250     
_________________________________________________________________
dense_14 (Dense)             (None, 250)               12750     
_________________________________________________________________
dropout_1 (Dropout)          (None, 250)               0         
_________________________________________________________________
dense_15 (Dense)             (None, 10)                2510      
Total params: 54,510
Trainable params: 54,510
Non-trainable params: 0
_________________________________________________________________


Vemos que el número de parámetros a entrenar es el mismo, Dropout no añade pesos a la red

In [36]:
modelo_dropout.fit(x_train_plano, y_train_one_hot, verbose=0, epochs=50, batch_size=1000);

In [37]:
acc_train = modelo_dropout.evaluate(x_train_plano, y_train_one_hot)[1]
acc_test = modelo_dropout.evaluate(x_test_plano, y_test_one_hot)[1]

10000/10000 [==============================] - 0s 28us/step


In [38]:
print(acc_train, acc_test)

0.985483333333 0.961


In [39]:
RESULTADOS["regularizacion_dropout"] = [acc_train, acc_test]

### Normalización en bloques (batch normalization)

In [40]:
from keras.layers import BatchNormalization

In [41]:
modelo_bnorm = Sequential()
modelo_bnorm.add(Dense(50, activation="relu", input_shape=(784,)))
modelo_bnorm.add(Dense(250, activation="relu"))
modelo_bnorm.add(BatchNormalization())
modelo_bnorm.add(Dense(np.unique(y_train).shape[0], activation="softmax"))

modelo_bnorm.compile(optimizer="sgd", loss="categorical_crossentropy", 
               metrics=["accuracy"])

modelo_bnorm.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 50)                39250     
_________________________________________________________________
dense_17 (Dense)             (None, 250)               12750     
_________________________________________________________________
batch_normalization_1 (Batch (None, 250)               1000      
_________________________________________________________________
dense_18 (Dense)             (None, 10)                2510      
Total params: 55,510
Trainable params: 55,010
Non-trainable params: 500
_________________________________________________________________


In [42]:
modelo_bnorm.fit(x_train_plano, y_train_one_hot, verbose=0, epochs=50, batch_size=1000)
acc_train = modelo_bnorm.evaluate(x_train_plano, y_train_one_hot)[1]
acc_test = modelo_bnorm.evaluate(x_test_plano, y_test_one_hot)[1]

RESULTADOS["batch_normalization"] = [acc_train, acc_test]
print(acc_train, acc_test)

10000/10000 [==============================] - 0s 39us/step
0.966166666667 0.9603


### Batch Normalization + Dropout

Una práctica común es poner normalizacion batch y dropout juntos en una capa

In [43]:
modelo_bnorm_drop = Sequential()
modelo_bnorm_drop.add(Dense(50, activation="relu", input_shape=(784,)))
modelo_bnorm_drop.add(Dense(250, activation="relu"))
modelo_bnorm_drop.add(BatchNormalization())
modelo_bnorm_drop.add(Dropout(0.2))
modelo_bnorm_drop.add(Dense(np.unique(y_train).shape[0], activation="softmax"))

modelo_bnorm_drop.compile(optimizer="sgd", loss="categorical_crossentropy", 
               metrics=["accuracy"])

modelo_bnorm_drop.fit(x_train_plano, y_train_one_hot, verbose=0, epochs=50, batch_size=1000)
acc_train = modelo_bnorm_drop.evaluate(x_train_plano, y_train_one_hot)[1]
acc_test = modelo_bnorm_drop.evaluate(x_test_plano, y_test_one_hot)[1]

RESULTADOS["batch_normalization + dropout"] = [acc_train, acc_test]
print(acc_train, acc_test)

10000/10000 [==============================] - 0s 37us/step
0.965883333333 0.9572


Ahora metemos los resultados en un dataframe para inspeccionarlos

In [44]:
import pandas as pd

resultados = pd.DataFrame(RESULTADOS).T
resultados.columns = ["acc_train", "acc_test"]
resultados["pct_diff"] = 1 - (resultados.acc_test / resultados.acc_train)

In [45]:
resultados.sort_values(by="pct_diff")

acc_train  acc_test  pct_diff
batch_normalization             0.966167    0.9603  0.006072
regularizacion_l1               0.958800    0.9504  0.008761
batch_normalization + dropout   0.965883    0.9572  0.008990
regularizacion_dropout          0.985483    0.9610  0.024844
regularizacion_l2               0.974633    0.9487  0.026608
sin_regularizacion              0.993417    0.9487  0.045013